const translations = {
    en: {
        // Navigation Elements
        "nav-home": "Home",
        "nav-food": "Food",
        "nav-attractions": "Attractions",
        "nav-music": "Music",
        "nav-streets": "Streets",
        "nav-book": "Book now",
        "nav-qr":"Contact Us",
        // Home Page Content
        "main-heading": "Information about Egypt",
        "main-text": "Egypt is a transcontinental country in Northeast Africa with a rich history, famous for its ancient civilization, the pyramids, and its capital city, Cairo. While its land area is vast, most of its over 100 million people live along the Nile River and its delta, as much of the rest of the country is desert. Modern Egypt has an economy driven by industries like tourism, agriculture, and textiles, and its cultural heritage is shaped by its ancient past as well as its more recent history as a hub for Christianity and then Islam.",
        "click-me": "click me",
        // Food Page Content
        "food1-title": "Mahshi",
        "food1-text": "Mahshi (Arabic for \"stuffed\") is a widely beloved, traditional dish across Egypt and the Middle East, cherished as the ultimate comfort food and a staple at family gatherings and celebrations. The dish is a vibrant assortment of various vegetables and leaves, such as zucchini, eggplant, bell peppers, tomatoes, cabbage, and grape leaves.",
        "food2-title": "Zalabia",
        "food2-text": "Zalabia is a highly popular and beloved Egyptian sweet treat, essentially the Middle Eastern equivalent of donut holes. Known also as Luqmat al-Qadi (meaning \"judge's morsels\"), these golden, bite-sized fried dough balls have a history tracing back to 10th-century Arabic cookbooks. They are a common and cherished street food, often sold in paper cones, and are a staple dessert particularly prevalent during the holy month of Ramadan.",
        "food3-title": "Koshari",
        "food3-text": "Koshari is Egypt's most famous and beloved street food. It is a lovely, filling dish made by layering rice, lentils, macaroni, and chickpeas. It is topped with a flavorful spiced tomato sauce, a tangy garlic vinegar, and that's it!",
        // Attractions Page Content
        "attr1-title": "Pyramids",
        "attr1-text": "The pyramids of ancient Egypt are some of the most magnificent and iconic structures in history, built primarily as elaborate tombs for the pharaohs and their consorts during the Old and Middle Kingdom periods, with the peak of construction occurring around 4,500 years ago.",
        "attr2-title": "Nile River",
        "attr2-text": "The Nile River is the longest river in Africa and historically vital to civilizations like ancient Egypt, providing water, fertile soil, and a transportation route. It flows northward through 11 countries before emptying into the Mediterranean Sea and is fed by two main tributaries, the White Nile and the Blue Nile, which join in Khartoum, Sudan. Ancient Egyptians used the river's annual floods to enrich their lands, and it played a central role in their economy, culture, and religious beliefs.",
         "attr3-title": "Abu Simbel Temple",
"attr3-text": "The Abu Simbel Temples are two massive rock-cut monuments located on the western bank of Lake Nasser in Nubia, southern Egypt. Carved out of a sandstone cliff during the 13th century BC under King Ramesses II, they serve as a grand monument to his reign, his historic battle of Kadesh, and his beloved wife, Queen Nefertari.",

"attr4-title": "Grand Egyptian Museum",
"attr4-text": "The Grand Egyptian Museum (GEM) is the world's largest archaeological museum dedicated to a single civilization. Located on the Giza Plateau next to the Great Pyramids, it houses over 100,000 ancient artifacts and the complete collection of Tutankhamun's treasures.",


        // Streets Page Content
        "street1-title": "Muizz Street",
        "street1-text": "Al-Muizz Street is the vibrant historic heart of Islamic Cairo and one of the world's most spectacular open-air museums. Stretching for nearly one kilometer, this pedestrian-friendly thoroughfare contains the largest and densest concentration of medieval architectural treasures in the Islamic world. Walking along its cobblestones reveals an overwhelming display of towering minarets, stunning Fatimid and Mamluk mosques, historic schoolhouses (madrasas), and ornate public water fountains.",
        "street2-title": "Fouad Street",
        "street2-text": "Fouad Street (Tareek El Horeya) is Alexandria’s most iconic and historic thoroughfare. Tracing its roots back to 331 BC, it is widely considered the world's oldest continuously inhabited planned street. It is famed for its European-style Belle Époque architecture, fine dining, and vibrant arts scene.",
        "street3-title": "Corniche Street",
        "street3-text": "The Alexandria Corniche is a scenic 17-kilometer waterfront promenade along the Mediterranean Sea, stretching from Qaitbay Citadel to Montaza Palace. As the city's vibrant heart, it features beautiful beaches, historic architecture, bustling cafes, and iconic landmarks like Stanley Bridge. It is the ultimate spot to enjoy fresh sea breezes and stunning coastal sunsets.",
        // Music Page Content
        "music1-title": "Egyptian Ney",
        "music1-text": "The ney (/neɪ/; Persian: نی) is an end-blown flute that figures prominently in traditional Persian, Turkish, Jewish, Arab, and Egyptian music. In some of these musical traditions, it is the only wind instrument used. The ney has been played for over 4,500 years, dating back to ancient Egypt, making it one of the oldest musical instruments still in use.",
        "music2-title": "Golden Harp",
        "music2-text": "The term \"golden harp\" carries rich symbolic, mythological, and cultural significance across various contexts, often representing musical excellence, divine connection, or a key element in folklore. In Greek mythology, a golden harp (or lyre) was gifted to Orpheus by the god Apollo, the music of which could charm everything from animals to gods and even the elements of the underworld. This highlights the instrument as an emblem of creativity and artistic expression.",
        // Form Page Content
        "form-title": "Visit Egypt",
        "form-subtitle": "Please enter your information",
        "lbl-name": "Name",
        "lbl-email": "Email",
        "lbl-phone": "Phone Number",
        "lbl-gender": "Gender",
        "lbl-male": "Male",
        "lbl-female": "Female",
        "lbl-arrival": "Arrival Date",
        "lbl-departure": "Departure Date",
        "lbl-passport": "Passport",
        "lbl-destination": "Where would you like to travel?",
        "opt-choose": "Choose one",
        "lbl-services": "Choose the services you need",
        "chk-tickets": "Airline Tickets",
        "chk-car": "Rental Car",
        "chk-hotel": "Hotel",
        "btn-submit": "Submit",
        "btn-reset": "Reset",
        "plh-name": "Enter your full name",
        "plh-email": "Enter your email",
        "plh-phone": "Enter your phone number",
        "qr-title": "Contact Us",
        "qr-description":"Scan the QR code below to access our exclusive content and offers!",
    },
    ar: {
        "nav-home": "الرئيسية",
        "nav-food": "الطعام",
        "nav-attractions": "المعالم السياحية",
        "nav-music": "الموسيقى",
        "nav-streets": "الشوارع",
        "nav-book": "احجز الآن",
        "nav-qr":"تواصل معنا",
        "main-heading": "معلومات عن مصر",
        "main-text": "مصر دولة عابرة للقارات تقع في شمال شرق أفريقيا وتتمتع بتاريخ غني، وتشتهر بحضارتها القديمة والأهرامات وعاصمتها القاهرة. ورغم أن مساحة أراضيها شاسعة، فإن أغلب سكانها الذين يتجاوز عددهم 100 مليون نسمة يعيشون على طول نهر النيل ودلتاه، حيث تشكل الصحراء بقية مساحة البلاد. وتتميز مصر الحديثة باقتصاد تقوده صناعات مثل السياحة والزراعة والمنسوجات، وتتشكل هويتها الثقافية من خلال ماضيها القديم وتاريخها الحديث كمركز للمسيحية ثم الإسلام.",
        "click-me": "اضغط هنا",
        "food1-title": "محشي",
        "food1-text": "المحشي هو طبق تقليدي محبوب للغاية في جميع أنحاء مصر والشرق الأوسط، ويُعتبر الطعام المريح الأمثل وعنصرًا أساسيًا في التجمعات العائلية والاحتفالات. الطبق عبارة عن تشكيلة حيوية من الخضروات والأوراق المختلفة، مثل الكوسة والباذنجان والفلفل الرومي والطماطم والكرنب وورق العنب.",
        "food2-title": "زلابية",
        "food2-text": "الزلابية هي حلوى مصرية شعبية ومحبوبة للغاية، وهي بمثابة المعادل الشرق أوسطي لكرات الدونات. تُعرف أيضًا باسم لقمة القاضي، وتعود أصول هذه الكرات الذهبية المقلية من العجين إلى كتب الطهي العربية في القرن العاشر. وهي من أطعمة الشوارع الشائعة والمحبوبة، وغالبًا ما تُباع في قراطيس ورقية، وهي حلوى أساسية منتشرة بشكل خاص خلال شهر رمضان المبارك.",
        "food3-title": "كشري",
        "food3-text": "الكشري هو أشهر وأحب أطعمة الشوارع في مصر. إنه طبق رائع ومُشبع يتم إعداده عن طريق وضع طبقات من الأرز والعدس والمعكرونة والحمص، وتُغطى بصلصة الطماطم المتبلة اللذيذة ودقة الثوم والخل والليمون!",
        "attr1-title": "الأهرامات",
        "attr1-text": "تعتبر أهرامات مصر القديمة من أكثر الهياكل روعة وإيقونية في التاريخ، وقد بنيت في المقام الأول كمقابر متقنة للفراعنة وزوجاتهم خلال فترات الدولتين القديمة والوسطى، حيث بلغت ذروة البناء قبل حوالي 4500 عام.",
        "attr2-title": "نهر النيل",
        "attr2-text": "نهر النيل هو أطول نهر في إفريقيا وله أهمية حيوية تاريخية للحضارات مثل مصر القديمة، حيث يوفر المياه والتربة الخصبة وطريقًا للنقل. يتدفق شمالًا عبر 11 دولة قبل أن يصب في البحر الأبيض المتوسط ​​ويتغذى على رافدين رئيسيين، النيل الأبيض والنيل الأزرق، اللذين يلتقيان في الخرطوم، السودان. استخدم المصريون القدماء الفيضانات السنوية للنهر لإثراء أراضيهم، ولعب دورًا مركزيًا في اقتصادهم وثقافتهم ومعتقداتهم الدينية.",
        "attr3-title":"معبد ابو سمبل",
        "attr3-text":"معبدا أبو سمبل هما صرحان ضخمان منحوتان في الصخر، يقعان على الضفة الغربية لبحيرة ناصر في النوبة، جنوب مصر. نُحتا من جرف من الحجر الرملي خلال القرن الثالث عشر قبل الميلاد في عهد الملك رمسيس الثاني، وهما بمثابة نصب تذكاري عظيم لحكمه، ومعركته التاريخية في قادش، وزوجته المحبوبة الملكة نفرتاري",
        "attr4-title":"المتحف المصري الكبير",
        "attr4-text":"يُعدّ المتحف المصري الكبير أكبر متحف أثري في العالم مُخصّص لحضارة واحدة. يقع هذا الصرح المعماري الرائع على هضبة الجيزة بجوار الأهرامات، ويمتد على مساحة تقارب 500 ألف متر مربع. يضم المتحف مجموعة استثنائية تضم أكثر من 100 ألف قطعة أثرية قديمة، تربط آلاف السنين من التاريخ المصري. بعد افتتاحه الرسمي للجمهور، والذي طال انتظاره، يعرض المتحف المجموعة الكاملة لكنوز الملك توت عنخ آمون لأول مرة منذ اكتشافها عام 1922. تمزج صالات العرض الحديثة والمُكيّفة وواجهته الحجرية الضخمة الشفافة بسلاسة بين أحدث تقنيات القرن الحادي والعشرين وعظمة الآثار القديمة.",
        "street1-title": "شارع المعز",
        "street1-text": "شارع المعز هو القلب التاريخي النابض للقاهرة الإسلامية وأحد أروع المتاحف المفتوحة في العالم. يمتد هذا الشارع المخصص للمشاة لمسافة كيلومتر واحد تقريبًا، ويحتوي على أكبر وأكثف تجمع للكنوز المعمارية من العصور الوسطى في العالم الإسلامي. تكشف السير على أحجاره عن عرض مذهل للمآذن الشاهقة، والمساجد الفاطمية والمملوكية الرائعة، والمدارس التاريخية، والسبل المزخرفة.",
        "street2-title": "شارع فؤاد",
        "street2-text": "شارع فؤاد (طريق الحرية) هو الشارع الأكثر شهرة وتاريخًا في الإسكندرية. تعود جذوره إلى عام 331 قبل الميلاد، ويعتبر على نطاق واسع أقدم شارع مخطط مأهول باستمرار في العالم. يشتهر بهندسته المعمارية الأوروبية المبنية على طراز العصر الجميل، والمطاعم الفاخرة، والمشهد الفني النابض بالحياة.",
        "street3-title": "شارع الكورنيش",
        "street3-text": "كورنيش الإسكندرية هو ممشى ساحلي خلاب يمتد لمسافة 17 كيلومترًا على طول البحر الأبيض المتوسط، من قلعة قايتباي إلى قصر المنتزه. وباعتباره القلب النابض للمدينة، فهو يتميز بشواطئ جميلة، وهندسة معمارية تاريخية، ومقاهي صاخبة، ومعالم بارزة مثل كوبري ستانلي. إنه المكان الأمثل للاستمتاع بنسيم البحر المنعش وغروب الشمس الساحلي.",
        "music1-title": "الناي المصري",
        "music1-text": "الناي عبارة عن فلوت يُنفخ من طرفه ويظهر بشكل بارز في الموسيقى التقليدية الفارسية والتركية واليهودية والعربية والمصرية. في بعض هذه التقاليد الموسيقية، هو الآلة الهوائية الوحيدة المستخدمة. تم عزف الناي لأكثر من 4500 عام، ويعود تاريخه إلى مصر القديمة، مما يجعله واحدًا من أقدم الآلات الموسيقية التي لا تزال قيد الاستخدام.",
        "music2-title": "الهارب الذهبي",
        "music2-text": "يحمل مصطلح 'الهارب الذهبي' أهمية رمزية وميثولوجية وثقافية غنية عبر سياقات مختلفة، وغالبًا ما يمثل التميز الموسيقي أو الاتصال الإلهي أو عنصرًا أساسيًا في الفولكلور. في الأساطير اليونانية، تم إهداء قيثارة ذهبية (أو ليرة) لأورفيوس من قبل الإله أبولو، والتي يمكن لموسيقاها أن تسحر كل شيء من الحيوانات إلى الآلهة وحتى عناصر العالم السفلي. هذا يسلط الضوء على الآلة كرمز للإبداع والتعبير الفني.",
        "form-title": "قم بزيارة مصر",
        "form-subtitle": "يرجى إدخال معلوماتك",
        "lbl-name": "الاسم",
        "lbl-email": "البريد الإلكتروني",
        "lbl-phone": "رقم الهاتف",
        "lbl-gender": "الجنس",
        "lbl-male": "ذكر",
        "lbl-female": "أنثى",
        "lbl-arrival": "تاريخ الوصول",
        "lbl-departure": "تاريخ المغادرة",
        "lbl-passport": "جواز السفر",
        "lbl-destination": "أين تود السفر؟",
        "opt-choose": "اختر مكانًا واحدًا",
        "lbl-services": "اختر الخدمات التي تحتاجها",
        "chk-tickets": "تذاكر الطيران",
        "chk-car": "تأجير سيارات",
        "chk-hotel": "حجز فندق",
        "btn-submit": "إرسال",
        "btn-reset": "إعادة تعيين",
        "plh-name": "أدخل اسمك الكامل",
        "plh-email": "أدخل بريدك الإلكتروني",
        "plh-phone": "أدخل رقم هاتفك",
        "qr-title":"تواصل معنا",
        "qr-description": "امسح رمز الاستجابة السريعة أدناه للوصول إلى محتوانا وعروضنا الحصرية!",
    },
    ru: {
        "nav-home": "Главная",
        "nav-food": "Еда",
        "nav-attractions": "Достопримечательности",
        "nav-music": "Музыка",
        "nav-streets": "Улицы",
        "nav-book": "Забронировать",
        "nav-qr": "Cвя3aтьcя c нами",
        "main-heading": "Информация об Египте",
        "main-text": "Египет — трансконтинентальная страна в Северо-Восточной Африке с богатой историей, известная своей древней цивилизацией, пирамидами и столицей Каиром. Хотя его территория огромна, большинство из более чем 100-миллионного населения проживает вдоль реки Нил и ее дельты, так как большая часть остальной территории страны представляет собой пустыню. Экономика современного Египта держится на таких отраслях, как туризм, сельское хозяйство и текстильная промышленность, а его культурное наследие сформировано как древним прошлым, так и более поздней историей как центра христианства, а затем и ислама.",
        "click-me": "нажми на меня",
        "food1-title": "Махши",
        "food1-text": "Махши (в переводе с арабского «фаршированный») — это всеми любимое традиционное блюдо в Египте и на Ближнем Востоке, считающееся главной домашней едой и обязательным угощением на семейных праздниках. Блюдо представляет собой яркое ассорти из различных овощей и листьев, таких как кабачки, баклажаны, болгарский перец, помидоры, капуста и виноградные листья.",
        "food2-title": "Залабия",
        "food2-text": "Залабия — это очень популярное и любимое египетское сладкое лакомство, ближневосточный аналог пончиков. Эти золотистые обжаренные во фритюре шарики из теста, также известные как Лукмат аль-Кади («кусочки судьи»), упоминаются еще в арабских кулинарных книгах X века. Это популярная уличная еда, которую часто продают в бумажных кульках, и традиционный десерт, особенно популярный в священный месяц Рамадан.",
        "food3-title": "Кошари",
        "food3-text": "Кошари — самая известная и любимая уличная еда в Египте. Это сытное и вкусное блюдо, состоящее из слоев риса, чечевицы, макарон и нута. Сверху его поливают пикантным пряным томатным соусом, чесночным уксусом, и готово!",
        "attr1-title": "Пирамиды",
        "attr1-text": "Пирамиды древнего Египта — одни из самых великолепных и культовых сооружений в истории, построенные в основном как тщательно продуманные гробницы для фараонов и их супруг в периоды Древнего и Среднего царств, причем пик строительства пришелся примерно на 4500 лет назад.",
        "attr2-title": "Река Нил",
        "attr2-text": "Река Нил — самая длинная река в Африке, исторически важная для таких цивилизаций, как древний Египет, обеспечивавшая воду, плодородную почву и транспортный маршрут. Она течет на север через 11 стран, прежде чем впасть в Средиземное море, и питается двумя основными притоками — Белым Нилом и Голубым Нилом, которые соединяются в Хартуме, Судан. Древние египтяне использовали ежегодные разливы реки для обогащения своих земель, и она играла центральную роль в их экономике, культуре и религиозных верованиях.",
        "attr3-title": "Храм Абу-Симбел",
"attr3-text": "Храмы Абу-Симбел представляют собой два огромных высеченных в скале памятника на западном берегу озера Насер на юге Египта. Они были созданы во времена фараона Рамсеса II и посвящены его правлению и царице Нефертари.",

"attr4-title": "Большой Египетский музей",
"attr4-text": "Большой Египетский музей является крупнейшим археологическим музеем в мире, посвящённым одной цивилизации. Он расположен рядом с пирамидами Гизы и хранит более 100 000 древних артефактов.",
        "street1-title": "Улица Муизз",
        "street1-text": "Улица Аль-Муизз — это яркое историческое сердце исламского Каира и один из самых впечатляющих в мире музеев под открытым небом. Эта пешеходная магистраль протяженностью почти один километр содержит самую большую и плотную концентрацию средневековых архитектурных сокровищ в исламском мире. Прогулка по ее булыжникам открывает потрясающее зрелище высоких минаретов, великолепных мечетей Фатимидов и Мамлюков, исторических школ (мадресе) и богато украшенных общественных фонтанов.",
        "street2-title": "Улица Фуад",
        "street2-text": "Улица Фуад (Тарик Эль-Хорейя) — самая известная и историческая магистраль Александрии. Беря свое начало в 331 году до н.э., она считается старейшей в мире непрерывно заселенной спланированной улицей. Она знаменита своей европейской архитектурой в стиле Belle Époque, изысканной кухней и яркой художественной сценой.",
        "street3-title": "Улица Корниш",
        "street3-text": "Александрийская набережная Корниш — это живописный 17-километровый прибрежный променад вдоль Средиземного моря, тянущийся от цитадели Кайтбей до дворца Монтаза. Являясь бьющимся сердцем города, она включает в себя прекрасные пляжи, историческую архитектуру, оживленные кафе и такие культовые достопримечательности, как мост Стэнли. Это идеальное место, чтобы насладиться свежим морским бризом и потрясающими прибрежными закатами.",
        "music1-title": "Египетский Ней",
        "music1-text": "Ней — это продольная флейта, которая занимает видное место в традиционной персидской, турецкой, еврейской, арабской и египетской музыке. В некоторых из этих музыкальных традиций это единственный используемый духовой инструмент. На нее играют уже более 4500 лет, начиная с древнего Египта, что делает его одним из старейших музыкальных инструментов, используемых до сих пор.",
        "music2-title": "Золотая Арфа",
        "music2-text": "Термин «золотая арфа» несет в себе богатое символическое, мифологическое и культурное значение в различных контекстах, часто представляя музыкальное мастерство, божественную связь или ключевой элемент фольклора. В греческой мифологии золотая арфа (или лира) была подарена Орфею богом Аполлоном, музыка которой могла очаровать все, от животных до богов и даже обитателей подземного мира. Это подчеркивает инструмент как эмблему творчества и художественного самовыражения.",
        "form-title": "Посетите Египет",
        "form-subtitle": "Пожалуйста, введите вашу информацию",
        "lbl-name": "Имя",
        "lbl-email": "Email",
        "lbl-phone": "Номер телефона",
        "lbl-gender": "Пол",
        "lbl-male": "Мужской",
        "lbl-female": "Женский",
        "lbl-arrival": "Дата прибытия",
        "lbl-departure": "Дата выезда",
        "lbl-passport": "Паспорт",
        "lbl-destination": "Куда бы вы хотели отправиться?",
        "opt-choose": "Выберите один вариант",
        "lbl-services": "Выберите необходимые услуги",
        "chk-tickets": "Авиабилеты",
        "chk-car": "Аренда автомобиля",
        "chk-hotel": "Отель",
        "btn-submit": "Отправить",
        "btn-reset": "Сбросить",
        "plh-name": "Введите ваше полное имя",
        "plh-email": "Введите ваш email",
        "plh-phone": "Введите ваш номер телефона",
        "qr-title": "Cвя3aтьcя c нами",
        "qr-description": "Отсканируйте QR-код ниже, чтобы получить доступ к нашему эксклюзивному контенту и предложениям!",
    },
    de: {
        "nav-home": "Startseite",
        "nav-food": "Essen",
        "nav-attractions": "Sehenswürdigkeiten",
        "nav-music": "Musik",
        "nav-streets": "Straßen",
        "nav-book": "Jetzt buchen",
        "nav-qr": "Kontaktieren Sie uns",
        "main-heading": "Informationen über Ägypten",
        "main-text": "Ägypten ist ein transkontinentales Land in Nordostafrika mit einer reichen Geschichte, bekannt für seine antike Zivilisation, die Pyramiden und seine Hauptstadt Kairo. Obwohl die Landfläche riesig ist, leben die meisten der über 100 Millionen Einwohner entlang des Nils und seines Deltas, da der Rest des Landes größtenteils aus Wüste besteht. Das moderne Ägypten hat eine Wirtschaft, die von Branchen wie Tourismus, Landwirtschaft und Textilien angetrieben wird, und sein kulturelles Erbe ist sowohl von seiner antiken Vergangenheit als auch von seiner jüngeren Geschichte als Zentrum des Christentums und später des Islams geprägt.",
        "click-me": "klick mich",
        "food1-title": "Mahshi",
        "food1-text": "Mahshi (arabisch für „gefüllt“) ist ein weithin beliebtes, traditionelles Gericht in ganz Ägypten und dem Nahen Osten. Es wird als das ultimative Seelenessen geschätzt und darf bei Familientreffen und Feierlichkeiten nicht fehlen. Das Gericht besteht aus einer bunten Auswahl verschiedener Gemüse und Blätter wie Zucchini, Auberginen, Paprika, Tomaten, Kohl und Weinblättern.",
        "food2-title": "Zalabia",
        "food2-text": "Zalabia ist eine sehr beliebte ägyptische Süßspeise, im Wesentlichen das nahöstliche Äquivalent zu Donut-Löchern. Diese goldenen, mundgerechten frittierten Teigbällchen, auch bekannt als Luqmat al-Qadi (was „Häppchen des Richters“ bedeutet), haben eine Geschichte, die bis in arabische Kochbücher des 10. Jahrhunderts zurückreicht. Sie sind ein beliebtes Streetfood, das oft in Papiertüten verkauft wird, und ein Grunddessert, das besonders im heiligen Monat Ramadan weit verbreitet ist.",
        "food3-title": "Koshari",
        "food3-text": "Koshari ist Ägyptens bekanntestes und beliebtestes Streetfood. Es ist ein wunderbares, sättigendes Gericht, das aus Schichten von Reis, Linsen, Makkaroni und Kichererbsen besteht. Es wird mit einer schmackhaften, gewürzten Tomatensauce und einem spritzigen Knoblauch-Essig-Dressing serviert – und das war's!",
        "attr1-title": "Pyramiden",
        "attr1-text": "Die Pyramiden des alten Ägypten gehören zu den prächtigsten und ikonischsten Bauwerken der Geschichte. Sie wurden hauptsächlich als aufwendige Gräber für die Pharaonen und ihre Gemahlinnen während des Alten und Mittleren Reiches errichtet, wobei der Höhepunkt der Bautätigkeit vor etwa 4.500 Jahren lag.",
        "attr2-title": "Nil",
        "attr2-text": "Der Nil ist der längste Fluss Afrikas und historisch von entscheidender Bedeutung für Zivilisationen wie das alte Ägypten, da er Wasser, fruchtbaren Boden und einen Transportweg bot. Er fließt nach Norden durch 11 Länder, bevor er in das Mittelmeer mündet, und wird von zwei Hauptnebenflüssen gespeist, dem Weißen Nil und dem Blauen Nil, die sich in Khartum (Sudan) vereinen. Die alten Ägypter nutzten die jährlichen Überschwemmungen des Flusses, um ihr Land fruchtbar zu machen, und er spielte eine zentrale Rolle in ihrer Wirtschaft, Kultur und ihren religiösen Vorstellungen.",
        "attr3-title": "Tempel von Abu Simbel",
"attr3-text": "Die Tempel von Abu Simbel sind zwei gewaltige Felsentempel am Westufer des Nassersees im Süden Ägyptens. Sie wurden im 13. Jahrhundert v. Chr. unter Ramses II. errichtet.",

"attr4-title": "Großes Ägyptisches Museum",
"attr4-text": "Das Große Ägyptische Museum ist das größte archäologische Museum der Welt, das einer einzigen Zivilisation gewidmet ist. Es befindet sich neben den Pyramiden von Gizeh und beherbergt über 100.000 Artefakte.",
        "street1-title": "Muizz-Straße",
        "street1-text": "Die Al-Muizz-Straße ist das lebendige historische Herz des islamischen Kairo und eines der spektakulärsten Freilichtmuseen der Welt. Auf einer Länge von fast einem Kilometer beherbergt diese Fußgängerzone die größte und dichteste Konzentration mittelalterlicher Architekturschätze in der islamischen Welt. Ein Spaziergang über das Kopfsteinpflaster offenbart eine überwältigende Pracht aus aufragenden Minaretten, atemberaubenden fatimidischen und mamlukischen Moscheen, historischen Schulen (Madrasas) und verzierten öffentlichen Brunnen.",
        "street2-title": "Fouad-Straße",
        "street2-text": "Die Fouad-Straße (Tareek El Horeya) ist die ikonischste und historischste Durchgangsstraße Alexandrias. Ihre Wurzeln reichen bis in das Jahr 331 v. Chr. zurück und sie gilt weithin als die älteste durchgehend bewohnte geplante Straße der Welt. Sie ist berühmt für ihre europäische Belle-Époque-Architektur, gehobene Gastronomie und eine lebendige Kunstszene.",
        "street3-title": "Corniche-Straße",
        "street3-text": "Die Corniche von Alexandria ist eine malerische, 17 Kilometer lange Uferpromenade am Mittelmeer, die sich von der Qaitbay-Zitadelle bis zum Montaza-Palast erstreckt. Als lebendiges Herz der Stadt bietet sie wunderschöne Strände, historische Architektur, belebte Cafés und ikonische Wahrzeichen wie die Stanley-Brücke. Es ist der ultimative Ort, um die frische Meeresbrise und atemberaubende Küstenuntergänge zu genießen.",
        "music1-title": "Ägyptischer Ney",
        "music1-text": "Die Ney ist eine Längsflöte, die in der traditionellen persischen, türkischen, jüdischen, arabischen und ägyptischen Musik eine wichtige Rolle spielt. In einigen dieser Musiktraditionen ist sie das einzige verwendete Blasinstrument. Die Ney wird seit über 4.500 Jahren gespielt und lässt sich bis ins alte Ägypten zurückverfolgen, was sie zu einem der ältesten heute noch verwendeten Musikinstrumente macht.",
        "music2-title": "Goldene Harfe",
        "music2-text": "Der Begriff „goldene Harfe“ besitzt in verschiedenen Kontexten eine reiche symbolische, mythologische und kulturelle Bedeutung und steht oft für musikalische Exzellenz, göttliche Verbindung oder ein Schlüsselelement der Folklore. In der griechischen Mythologie wurde Orpheus vom Gott Apollo eine goldene Harfe (oder Lyra) geschenkt, deren Musik alles von Tieren über Götter bis hin zu den Elementen der Unterwelt verzaubern konnte. Dies unterstreicht das Instrument als Emblem für Kreativität und künstlerischen Ausdruck.",
        "form-title": "Besuche Ägypten",
        "form-subtitle": "Bitte geben Sie Ihre Daten ein",
        "lbl-name": "Name",
        "lbl-email": "E-Mail",
        "lbl-phone": "Telefonnummer",
        "lbl-gender": "Geschlecht",
        "lbl-male": "Männlich",
        "lbl-female": "Weiblich",
        "lbl-arrival": "Anreisedatum",
        "lbl-departure": "Abreisedatum",
        "lbl-passport": "Reisepass",
        "lbl-destination": "Wohin möchten Sie reisen?",
        "opt-choose": "Bitte auswählen",
        "lbl-services": "Wählen Sie die benötigten Services",
        "chk-tickets": "Flugtickets",
        "chk-car": "Mietwagen",
        "chk-hotel": "Hotel",
        "btn-submit": "Absenden",
        "btn-reset": "Zurücksetzen",
        "plh-name": "Geben Sie Ihren vollständigen Namen ein",
        "plh-email": "Geben Sie Ihre E-Mail-Adresse ein",
        "plh-phone": "Geben Sie Ihre Telefonnummer ein",
        "qr-title" : "Kontaktieren Sie uns",
        "qr-description" : "Scannen Sie den unten stehenden QR-Code, um auf unsere exklusiven Inhalte und Angebote zuzugreifen!",

    },
    fr: {
        "nav-home": "Accueil",
        "nav-food": "Nourriture",
        "nav-attractions": "Attractions",
        "nav-music": "Musique",
        "nav-streets": "Rues",
        "nav-book": "Réserver",
        "nav-qr": "Contactez-nous",
        "main-heading": "Informations sur l'Égypte",
        "main-text": "L'Égypte est un pays transcontinental d'Afrique du Nord-Est doté d'une riche histoire, célèbre pour sa civilisation ancienne, ses pyramides et sa capitale, Le Caire. Bien que sa superficie soit vaste, la majeure partie de ses 100 millions d'habitants vit le long du Nil et de son delta, le reste du pays étant un désert. L'Égypte moderne possède une économie tirée par des industries comme le tourisme, l'agriculture et le textile, et son patrimoine culturel est façonné par son passé antique ainsi que par son histoire plus récente en tant que carrefour du christianisme puis de l'islam.",
        "click-me": "cliquez ici",
        "food1-title": "Mahshi",
        "food1-text": "Le Mahshi (qui signifie « farci » en arabe) est un plat traditionnel très apprécié en Égypte et au Moyen-Orient, considéré comme le réconfort absolu et un incontournable des réunions de famille et des célébrations. Ce plat se compose d'un assortiment coloré de divers légumes et feuilles, comme des courgettes, des aubergines, des poivrons, des tomates, du chou et des feuilles de vigne.",
        "food2-title": "Zalabia",
        "food2-text": "La Zalabia est une douceur égyptienne très populaire, l'équivalent oriental des beignets. Également connues sous le nom de Luqmat al-Qadi (qui signifie « les bouchées du juge »), ces boules de pâte frites dorées ont une histoire qui remonte aux livres de cuisine arabe du Xe siècle. C'est un produit de street food très apprécié, souvent vendu dans des cônes en papier, et un dessert incontournable, particulièrement présent pendant le mois saint du Ramadan.",
        "food3-title": "Koshari",
        "food3-text": "Le Koshari est le plat de rue le plus célèbre et le plus apprécié d'Égypte. C'est un plat savoureux et copieux composé de couches de riz, de lentilles, de macaronis et de pois chiches. Il est nappé d'une sauce tomate épicée et parfumée, d'un vinaigre à l'ail acidulé, et c'est tout !",
        "attr1-title": "Pyramides",
        "attr1-text": "Les pyramides de l'Égypte ancienne comptent parmi les structures les plus magnifiques et les plus emblématiques de l'histoire, construites principalement comme des tombeaux complexes pour les pharaons et leurs consorts pendant les périodes de l'Ancien et du Moyen Empire, le pic de la construction ayant eu lieu il y a environ 4 500 ans.",
        "attr2-title": "Le Nil",
        "attr2-text": "Le Nil est le plus long fleuve d'Afrique et s'est révélé historiquement vital pour les civilisations comme l'Égypte ancienne, fournissant de l'eau, un sol fertile et une voie de transport. Il coule vers le nord à travers 11 pays avant de se jeter dans la mer Méditerranée et est alimenté par deux affluents principaux, le Nil Blanc et le Nil Bleu, qui se rejoignent à Khartoum, au Soudan. Les anciens Égyptiens utilisaient les crues annuelles du fleuve pour enrichir leurs terres, et il a joué un rôle central dans leur économie, leur culture et leurs croyances religieuses.",
        "attr3-title": "Temple d'Abou Simbel",
"attr3-text": "Les temples d'Abou Simbel sont deux immenses monuments taillés dans la roche situés sur la rive ouest du lac Nasser, dans le sud de l'Égypte. Ils ont été construits sous le règne de Ramsès II.",

"attr4-title": "Grand Musée Égyptien",
"attr4-text": "Le Grand Musée Égyptien est le plus grand musée archéologique au monde consacré à une seule civilisation. Situé près des pyramides de Gizeh, il abrite plus de 100 000 artefacts antiques.",
        "street1-title": "Rue Al-Muizz",
        "street1-text": "La rue Al-Muizz est le cœur historique dynamique du Caire islamique et l'un des musées en plein air les plus spectaculaires au monde. S'étendant sur près d'un kilomètre, cette artère piétonne abrite la plus grande et la plus dense concentration de trésors architecturaux médiévaux du monde islamique. Flâner sur ses pavés révèle un spectacle saisissant de minarets imposants, de superbes mosquées fatimides et mameloukes, d'écoles historiques (madrasas) et de fontaines publiques ornées.",
        "street2-title": "Rue Fouad",
        "street2-text": "La rue Fouad (Tareek El Horeya) est l'artère la plus emblématique et historique d'Alexandrie. Trouvant ses racines en 331 avant J.-C., elle est largement considérée comme la plus ancienne rue planifiée et continuellement habitée au monde. Elle est réputée pour son architecture européenne Belle Époque, ses restaurants raffinés et sa scène artistique animée.",
        "street3-title": "Rue de la Corniche",
        "street3-text": "La Corniche d'Alexandrie est une promenade pittoresque de 17 kilomètres au bord de la mer Méditerranée, s'étendant de la citadelle de Qaitbay au palais de Montaza. Cœur vibrant de la ville, elle offre de belles plages, une architecture historique, des cafés animés et des monuments emblématiques comme le pont Stanley. C'est l'endroit idéal pour profiter de la brise marine fraîche et de magnifiques couchers de soleil côtiers.",
        "music1-title": "Ney Égyptien",
        "music1-text": "Le ney est une flûte à embouchure terminale qui occupe une place importante dans la musique traditionnelle persane, turque, juive, arabe et égyptienne. Dans certaines de ces traditions musicales, c'est le seul instrument à vent utilisé. Le ney est joué depuis plus de 4 500 ans, remontant à l'Égypte ancienne, ce qui en fait l'un des plus anciens instruments de musique encore en usage.",
        "music2-title": "Harpe Dorée",
        "music2-text": "Le terme « harpe dorée » revêt une riche signification symbolique, mythologique et culturelle dans divers contextes, représentant souvent l'excellence musicale, la connexion divine ou un élément clé du folklore. Dans la mythologie grecque, une harpe dorée (ou lyre) a été offerte à Orphée par le dieu Apollon, dont la musique pouvait charmer tout, des animaux aux dieux et même les éléments des enfers. Cela met en lumière l'instrument comme un emblème de créativité et d'expression artistique.",
        "form-title": "Visitez l'Égypte",
        "form-subtitle": "Veuillez entrer vos informations",
        "lbl-name": "Nom",
        "lbl-email": "E-mail",
        "lbl-phone": "Numéro de téléphone",
        "lbl-gender": "Genre",
        "lbl-male": "Homme",
        "lbl-female": "Femme",
        "lbl-arrival": "Date d'arrivée",
        "lbl-departure": "Date de départ",
        "lbl-passport": "Passeport",
        "lbl-destination": "Où aimeriez-vous voyager ?",
        "opt-choose": "Choisissez une option",
        "lbl-services": "Choisissez les services dont vous avez besoin",
        "chk-tickets": "Billets d'avion",
        "chk-car": "Location de voiture",
        "chk-hotel": "Hôtel",
        "btn-submit": "Soumettre",
        "btn-reset": "Réinitialiser",
        "plh-name": "Entrez votre nom complet",
        "plh-email": "Entrez votre e-mail",
        "plh-phone": "Entrez votre numéro de téléphone",
        "qr-title" : "Contactez-nous",
        "qr-decription" : "Scannez le code QR ci-dessous pour accéder à notre contenu et à nos offres exclusifs !",
    }
};

const languageSelect = document.getElementById('language-select');

// Core Translate Action Engine
function applyLanguage(lang) {
    const elementsToTranslate = document.querySelectorAll('[data-key]');
    
    elementsToTranslate.forEach(element => {
        const key = element.getAttribute('data-key');
        if (translations[lang] && translations[lang][key]) {
            // Check if element is an input placeholder
            if (element.tagName === 'INPUT' && element.hasAttribute('placeholder')) {
                element.setAttribute('placeholder', translations[lang][key]);
            } else if (element.tagName === 'INPUT' && (element.type === 'submit' || element.type === 'reset')) {
                element.value = translations[lang][key];
            } else {
                element.textContent = translations[lang][key];
            }
        }
    });

    // Mirror View Direction for Right-To-Left Text (Arabic Layouts)
    if (lang === 'ar') {
        document.body.style.direction = 'rtl';
    } else {
        document.body.style.direction = 'ltr';
    }

    // sync active page dropdown select option visually
    if (languageSelect) {
        languageSelect.value = lang;
    }
}

// Check saved localStorage choices when page DOM loads
document.addEventListener("DOMContentLoaded", () => {
    const savedLanguage = localStorage.getItem('selectedLanguage') || 'en';
    applyLanguage(savedLanguage);
});

// Listener tracking changes to save selections application-wide
if (languageSelect) {
    languageSelect.addEventListener('change', (event) => {
        const targetLanguage = event.target.value;
        localStorage.setItem('selectedLanguage', targetLanguage);
        applyLanguage(targetLanguage);
    });
}
